[build]
command = "yarn build"
publish = "example/public/"

[functions]
directory = "example/netlify/functions/"
external_node_modules = ["fsevents"]

[[redirects]]
from = "/_gatsby/image/*"
to = "/.netlify/builders/gatsby"
status = 200
