name: Label PR
on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr:
          [
            { prefix: 'fix', type: 'bug' },
            { prefix: 'chore', type: 'chore' },
            { prefix: 'docs', type: 'chore' },
            { prefix: 'test', type: 'chore' },
            { prefix: 'ci', type: 'chore' },
            { prefix: 'feat', type: 'feature' },
            { prefix: 'security', type: 'security' },
          ]
    steps:
      - uses: netlify/pr-labeler-action@v1.0.0
        if: startsWith(github.event.pull_request.title, matrix.pr.prefix)
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: 'type: ${{ matrix.pr.type }}'
